### ISSUE TITLE
Rename ModelStore method `dispatch` to `getDispatch`

### ISSUE THREAD

**Issue by djlauk** [CaptainCodeman/rdx#16]
For consistency with `ModelStore.getState()`, rename `dispatch()` to `getDispatch()`.

This will also reduce confusion, as the `dispatch` method is already serving double duty:

- As a function: The low level API for dispatching an Action (Event) within Rdx
- As an object: The mapping, where the strongly typed action creators are stored (generated from a model's reducers and effects).

**Comment by CaptainCodeman** [comment]
Yeah, I've been meaning to address this for ages but kept putting it off due to the other work it would cause. But it's an easy change to update dependent projects and it does make things clearer and now's the time to do it, before v1 is released.
