### ISSUE TITLE
Integrate rdx-model with rdx

### ISSUE THREAD

**Issue by djlauk** [CaptainCodeman/rdx#5]
Let's get this discussion out of slack and next to the code:

I suggest integrating rdx-model into rdx, as I actually cannot imagine ever using rdx without the convenience of rdx-model.

**Comment by djlauk** [comment]
Is this something you'd rather do yourself, or should/can I give it a try? (I have no clue, how involved that task is going to be, though.)

**Comment by CaptainCodeman** [comment]
This made total sense, now completed
