### ISSUE TITLE
Dark and light mode with switch

### ISSUE THREAD

**Issue by boopathikumar018** [CaptainCodeman/rdx#8]
Hi

Let me know if you would like to add [docsify-darklight-theme](https://docsify-darklight-theme.boopathikumar.me/#/) for you docsify documentation. I will give PR

**Comment by CaptainCodeman** [comment]
Sure, looks useful - thanks!

**Comment by boopathikumar018** [comment]
Hi @CaptainCodeman ,

Please find the [PR](https://github.com/CaptainCodeman/rdx/pull/9). Kindly check and merge

**Comment by CaptainCodeman** [comment]
Awesome, merged and thanks :)
